organization_name: Simple SSO

log_directory: log

log_level: Logger::DEBUG

cas_database:
  adapter: sqlite3
  database: db/cas.db
  timeout: 5000

cas_adapter:
  adapter: demo

#cas_adapter:
#  adapter: database
#  site_key: 03523your093023site0985225key098290here9
#  digest_stretches: 10
#  database:
#    adapter: sqlite3
#    database: db/cas_adapter.db
#    timeout: 5000
      
# Use this example if you are using LDAP as your authentication source
# cas_adapter:
#   adapter: ldap
#   host: localhost
#   port: 389
#   prefix: cn=
#   base: dc=example, dc=com

# Uncomment these to enable authentication callbacks
# callbacks:
#  on_authentication_success: http://example.com/authentication/success
#  on_authentication_failed: http://example.com/authentication/failed

extra_ui_actions:
  'Forgot Password': http://example.com/
